### ISSUE TITLE
implement a kubernetes runtime for linux executor 

### ISSUE THREAD

**Issue by kneal** [go-vela/worker#57]
## Description

_What is your idea?_

## Value

_Why is this important? Who does it impact? Will this make something better, faster, etc?_

## Definition of Done

_What is the end goal of this story?_

## Effort  (Optional)

_Estimated effort to complete this story? (Best Guess e.g. 1-2 days)_

## Impacted Personas (Optional)

_Which personas will benefit from completing this story? (Users, Administrators, etc)_

**Comment by jbrockopp** [comment]
@kneal and I are going to begin by writing the ability to create volumes in Kubernetes.

It appears the [gitRepo](https://kubernetes.io/docs/concepts/storage/volumes/#gitrepo) volume type is deprecated:

> Warning: The gitRepo volume type is deprecated. To provision a container with a git repo, mount an EmptyDir into an InitContainer that clones the repo using git, then mount the EmptyDir into the Pod’s container.

We will follow the recommended guidelines to use [emptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) instead 👍

**Comment by jbrockopp** [comment]
After some trial and error, we've come to a roadblock 😞 

Unfortunately, it would appear that Kubernetes prevents the ability to patch specific fields in a `Pod`. Specifically, it appears that we're unable to patch some `Container` fields which is required to maintain a "1 pod per build" strategy.

The initial plan was to create a single pod per build, and then to patch that pod with each container (step) from the pipeline.

The error message we receive:

```sh
spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
```

Issue with more information:

https://github.com/kubernetes/kubernetes/issues/9043

**Comment by jbrockopp** [comment]
Create separate runtime package:

https://github.com/go-vela/pkg-runtime/pull/1

**Comment by jbrockopp** [comment]
Store Kubernetes pod in client struct:

https://github.com/go-vela/pkg-runtime/pull/2

**Comment by jbrockopp** [comment]
Use the go-vela/compiler for our runtime CLI:

https://github.com/go-vela/pkg-runtime/pull/3

**Comment by jbrockopp** [comment]
Create a working runtime CLI:

https://github.com/go-vela/pkg-runtime/pull/4

**Comment by jbrockopp** [comment]
Add container wait logic for Kubernetes:

https://github.com/go-vela/pkg-runtime/pull/5

**Comment by jbrockopp** [comment]
Add container tail logic for Kubernetes:

https://github.com/go-vela/pkg-runtime/pull/6

**Comment by jbrockopp** [comment]
Use default (strategic merge) patch for Kubernetes pods:

https://github.com/go-vela/pkg-runtime/pull/7

**Comment by jbrockopp** [comment]
Add logic to remove Kubernetes resources:

https://github.com/go-vela/pkg-runtime/pull/8

**Comment by kneal** [comment]
Tune Kubernetes tail backoff for large pipelines
https://github.com/go-vela/pkg-runtime/pull/9

**Comment by kneal** [comment]
Implement the inspect process for Kubernetes
https://github.com/go-vela/pkg-runtime/pull/10

**Comment by kneal** [comment]
Make the namespace configurable
https://github.com/go-vela/pkg-runtime/pull/11

**Comment by jbrockopp** [comment]
Add function to create new runtime:

https://github.com/go-vela/pkg-runtime/pull/12

**Comment by jbrockopp** [comment]
Add validate logic for runtime:

https://github.com/go-vela/pkg-runtime/pull/13

**Comment by jbrockopp** [comment]
Add actions pipeline:

https://github.com/go-vela/pkg-runtime/pull/14
