### ISSUE TITLE
Step is scrubbed when status is used in ruleset without "pending"

### ISSUE THREAD

**Issue by wass3r** [go-vela/worker#81]
When you define a step with ruleset such as:
```yaml
ruleset:
  status: [success, failure]
```
the step is scrubbed from ever running.

Currently, you have to supply `pending` as a status for it to not get scrubbed at compile time, like:
```yaml
ruleset:
  status: [success, failure, pending]
```

Consider dropping the need to supply `pending` since it really works a bit differently conceptually than the other values.

Possible solutions:
- don't check status for scrubbing
- add `pending` automagically
- others?

**Comment by kneal** [comment]
This PR contains this fix so users no longer need to provide "pending" in the status to have the ruleset not be scrubbed.
https://github.com/go-vela/types/pull/59
